---
- name: Make sure the sonarr container is created and running
  docker_container:
    name: "sonarr"
    image: "ghcr.io/linuxserver/sonarr:latest"
    pull: yes
    networks:
      - name: app_network
    state: 'started'
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "{{ docker_dir }}/sonarr:/config"
      - "{{ mergerfs_root }}:/tank"
    restart_policy: unless-stopped
