---
- name: Create a wireguard network
  docker_network:
    name: wireguard_network

- name: Make sure wireguard container is created and running
  docker_container:
    name: 'wireguard'
    image: 'linuxserver/wireguard:latest'
    pull: yes
    networks:
      - name: wireguard_network
    capabilities:
      - net_admin
    env:
      'PUID': '{{ guid }}'
      'PGID': '{{ guid }}'
      'TZ': '{{ timezone }}'
    volumes:
      - '{{ docker_dir }}/wireguard/config:/config'
    ports:
      - "51820:51820"
    restart_policy: unless-stopped

- name: Make sure wireguard-ui container is created and running
  docker_container:
    name: 'wireguard-ui'
    image: 'ngoduykhanh/wireguard-ui:latest'
    pull: yes
    networks:
      - name: wireguard_network
      - name: app_network
    capabilities:
      - net_admin
    env:
      'WGUI_MANAGE_START': 'true'
      'WGUI_MANAGE_RESTART': 'true'
      'PUID': '{{ guid }}'
      'PGID': '{{ guid }}'
      'TZ': '{{ timezone }}'
    volumes:
      - '{{ docker_dir }}/wireguard/db:/app/db'
      - '{{ docker_dir }}/wireguard/config:/etc/wireguard'
    restart_policy: unless-stopped
