---
- name: Make sure the tdarr container is created and running
  docker_container:
    name: "tdarr"
    image: "ghcr.io/haveagitgat/tdarr:latest"
    pull: yes
    networks:
      - name: app_network
    state: 'started'
    device_requests:
      - driver: nvidia
        count: -1
        capabilities:
          - gpu
    log_driver: 'json-file'
    log_opt:
      max-size: '10m'
      max-file: '5'
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
      "serverIP": "0.0.0.0"
      "serverPort": "8266"
      "webUIPort": "8265"
      "internalNode": "true"
      "inContainer": "true"
      "ffmpegVersion": "6"
      "nodeName": "MyInternalNode"
      "NVIDIA_DRIVER_CAPABILITIES": "all"
      "NVIDIA_VISIBLE_DEVICES": "all"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "{{ docker_dir }}/tdarr/server:/app/server"
      - "{{ docker_dir }}/tdarr/configs:/app/configs"
      - "{{ docker_dir }}/tdarr/logs:/app/logs"
      - "{{ mergerfs_root }}/Media:/media"
      - "{{ mergerfs_root }}/Media/tdarr-transcodes:/temp"
    restart_policy: unless-stopped
