---
- name: Make sure the Flaresolverr container is created and running
  docker_container:
    name: "flaresolverr"
    image: "ghcr.io/flaresolverr/flaresolverr:latest"
    pull: yes
    networks:
      - name: app_network
    state: 'started'
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
    volumes:
      - "{{ docker_dir }}/flaresolverr:/config"
    restart_policy: unless-stopped
