---
#
# Tasks and roles for all hosts
#
- hosts: server
  gather_facts: no

  pre_tasks:
      - import_tasks: tasks/ssh_juggle_port.yml
        tags:
            - port

- hosts: server
  become: yes

  roles:
      #
      # Basics
      #
      - role: system
        tags:
            - system

      - role: neovim
        tags:
            - neovim

      - role: geerlingguy.security
        tags:
            - security

      # Filesystems
      #
      - role: filesystems/mergerfs
        become: yes
        tags:
            - mergerfs
        when: enable_nas_stuff | default(False)

      - role: filesystems/mounts
        become: yes
        tags:
            - mounts
        when: enable_nas_stuff | default(False)

      - role: docker
        tags:
            - docker

      - role: chriswayg.msmtp-mailer
        tags:
            - msmtp

      - role: oefenweb.dns
        tags:
            - dns

      - role: geerlingguy.ntp
        tags:
            - ntp

      - role: linux-system-roles.cockpit
        become: yes
        tags:
            - cockpit
        when: enable_cockpit | default(False)

      #
      # Security
      #
      - role: security/fail2ban
        tags:
            - fail2ban
        when: enable_fail2ban | default(False)

      - role: security/iptables
        tags:
            - iptables
        when: enable_iptables | default(False)

      - role: security/crowdsec
        tags:
            - crowdsec
        when: enable_crowdsec | default(False)

      - role: network/nginx-proxy-manager
        become: no
        tags:
            - nginx-proxy-manager
            - containers

      - role: network/cloudflare-ddns
        become: no
        tags:
            - cloudflare-ddns
            - containers
        when: enable_cloudflare_ddns | default(False)

      #
      - role: filesystems/hd-idle
        become: yes
        tags:
            - hd-idle
        when: enable_nas_stuff | default(False)

      - role: stuvusit.smartd
        become: yes
        tags:
            - smartd
        when: enable_nas_stuff | default(False)

      - role: ironicbadger.snapraid
        become: yes
        tags:
            - snapraid
        when: enable_nas_stuff | default(False)

      #
      # Flame
      #
      - role: containers/services/flame
        become: no
        tags:
            - flame
            - containers
        when: enable_flame | default(False)

      #
      # System
      #
      - role: containers/media/prowlarr
        become: no
        tags:
            - prowlarr
            - containers
        when: enable_prowlarr | default(False)

      - role: containers/media/flaresolverr
        become: no
        tags:
          - flaresolverr
          - containers
        when: enable_flaresolverr | default(False)

      - role: containers/media/unpackerr
        become: no
        tags:
            - unpackerr
            - containers
        when: enable_unpackerr | default(False)

      - role: containers/media/bazarr
        become: no
        tags:
            - bazarr
            - containers
        when: enable_bazarr | default(False)

      - role: containers/system/watchtower
        become: no
        tags:
            - watchtower
            - containers

      - role: containers/system/adguard
        become: no
        tags:
          - adguardhome
          - containers
        when: enable_adguard | default(False)

      #
      # Media
      #

      - role: containers/media/qbittorrent
        become: no
        tags:
            - qbittorrent
            - containers
        when: enable_qbittorrent | default(False)

      - role: containers/media/sonarr
        become: no
        tags:
            - sonarr
            - containers
        when: enable_sonarr | default(False)

      - role: containers/media/radarr
        become: no
        tags:
            - radarr
            - containers
        when: enable_radarr | default(False)

      - role: containers/media/lidarr
        become: no
        tags:
            - lidarr
            - containers
        when: enable_lidarr | default(False)

      - role: containers/media/jellyfin
        become: no
        tags:
            - jellyfin
            - containers
        when: enable_jellyfin | default(False)

      - role: containers/media/navidrome
        become: no
        tags:
            - navidrome
            - containers
        when: enable_navidrome | default(False)

      - role: containers/media/navidrome
        become: no
        tags:
            - navidrome
            - containers
        when: enable_navidrome | default(False)

      - role: containers/media/jellyseerr
        become: no
        tags:
            - jellyseerr
            - containers
        when: enable_jellyseerr | default(False)

      #
      # Services
      #
      - role: containers/services/photoprism
        become: no
        tags:
            - photoprism
            - containers
        when: enable_photoprism | default(False)

      - role: containers/services/gitea
        become: no
        tags:
            - gitea
            - containers
        when: enable_gitea | default(False)

      - role: containers/services/grocy
        become: no
        tags:
            - grocy
            - containers
        when: enable_grocy | default(False)

      - role: containers/services/invoiceninja
        become: no
        tags:
            - invoiceninja
            - containers
        when: enable_invoiceninja | default(False)

      - role: containers/services/paperless
        become: no
        tags:
            - paperless
            - containers
        when: enable_paperless | default(False)

      - role: containers/services/nextcloud
        become: no
        tags:
            - nextcloud
            - containers
        when: enable_nextcloud | default(False)

      - role: containers/services/vaultwarden
        become: no
        tags:
            - vaultwarden
            - containers
        when: enable_vaultwarden | default(False)

      - role: containers/services/gramps
        become: no
        tags:
            - gramps
            - containers
        when: enable_gramps | default(False)

      # #
      # # Samba
      # #
      # - role: bertvv.samba
      #   become: yes
      #   tags:
      #       - samba
      #   when: enable_nas_stuff | default(False)
