- name: Make sure the {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "fallenbagel/jellyseerr:latest"
    pull: yes
    networks:
      - name: app_network
    dns_servers:
      - 1.1.1.1
      - 8.8.8.8
    state: 'started'
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "{{ docker_dir }}/{{ container_name }}:/app/config"
    restart_policy: unless-stopped
