---
- name: Make sure the homarr container is created and running
  docker_container:
    name: 'homarr'
    image: ghcr.io/ajnart/homarr:latest
    networks:
        - name: app_network
    pull: yes
    state: 'started'
    volumes:
        - '{{ docker_dir }}/homarr/configs:/app/data/configs'
        - '{{ docker_dir }}/homarr/icons:/app/public/icons'
        - '{{ docker_dir }}/homarr/data:/data'
        - '/var/run/docker.sock:/var/run/docker.sock'
    restart_policy: unless-stopped
