---
- name: Make sure the Vaultwarden container is created and running
  docker_container:
    name: 'vaultwarden'
    image: "vaultwarden/server:latest"
    networks:
      - name: app_network
    pull: true
    state: 'started'
    env:
      WEBSOCKET_ENABLED: "true"
      INVITATIONS_ALLOWED: "false"
      SIGNUPS_ALLOWED: "false"
      DOMAIN: "https://vaultwarden.{{ host }}"
      LOG_FILE: "/data/vaultwarden.log"
      TZ: "{{ timezone }}"
    volumes:
      - "{{ docker_dir }}/vaultwarden:/data"
    restart_policy: unless-stopped
