---
- name: Install the VPN config
  copy:
    src: "files/wg0.conf"
    dest: "{{ docker_dir }}/qbittorrent/config/wireguard/"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644

- name: Make sure the qbittorrent container is created and running
  docker_container:
    name: "qbittorrent"
    image: "binhex/arch-qbittorrentvpn:latest"
    pull: yes
    networks:
      - name: app_network
    privileged: yes
    sysctls:
      "net.ipv4.conf.all.src_valid_mark": "1"
    capabilities:
      - net_admin
    state: 'started'
    ports:
      - "8118:8118"
    env:
      "WEBUI_PORT": "6017"
      "VPN_ENABLED": "yes"
      "VPN_PROV": "custom"
      "VPN_CLIENT": "wireguard"
      "ENABLE_PRIVOXY": "yes"
      "NAME_SERVERS": "{{ ','.join(dns_nameservers) }}"
      "LAN_NETWORK": "172.20.0.0/16, {{ lan_network }}"
      "UMASK": "000"
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
    volumes:
      - "{{ docker_dir }}/qbittorrent/data:/data"
      - "{{ docker_dir }}/qbittorrent/config:/config"
      - "{{ mergerfs_root }}:/tank"
      - "/etc/localtime:/etc/localtime:ro"
    restart_policy: unless-stopped
