---
- name: Chown the repo
  file:
      path: '/home/{{ username }}/.local/src/dotfiles'
      recurse: yes
      state: directory
      owner: '{{ username }}'
      group: '{{ username }}'

- name: Clone the latest dotfiles repo
  become_user: '{{ username }}'
  git:
      repo: '{{ dotfiles_repo }}'
      dest: '/home/{{ username }}/.local/src/dotfiles'
      recursive: no
      force: yes

- name: Create src dir
  file:
    path: "/home/{{ username }}/.local/src"
    state: directory
    owner: '{{ username }}'
    group: '{{ username }}'

- name: Stow the dotfiles
  become_user: '{{ username }}'
  shell:
      cmd: stow -v */
      chdir: '/home/{{ username }}/.local/src/dotfiles'
  register: stow_result
  notify:
      - install and update nvim plugins
  changed_when: stow_result.stdout != ""

- name: Create Zsh cache dir
  file:
    path: "/home/{{ username }}/.cache/zsh"
    state: directory
    owner: '{{ username }}'
    group: '{{ username }}'
