---
- name: Make sure the navidrome container is created and running
  docker_container:
    name: "navidrome"
    image: "deluan/navidrome:develop"
    pull: yes
    networks:
      - name: app_network
    state: 'started'
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
      "ND_SPOTIFY_ID": "{{ spotify_id }}"
      "ND_SPOTIFY_SECRET": "{{ spotify_secret }}"
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "{{ docker_dir }}/navidrome:/data"
      - "{{ mergerfs_root }}/Media/Music:/music:ro"
    restart_policy: unless-stopped
