---
- name: Make sure the radarr container is created and running
  docker_container:
    name: "radarr"
    image: "ghcr.io/linuxserver/radarr"
    pull: yes
    networks:
      - name: app_network
    state: 'started'
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "{{ docker_dir }}/radarr:/config"
      - "{{ mergerfs_root }}:/tank"
    restart_policy: unless-stopped
