---
- name: Make sure the unpackerr container is created and running
  docker_container:
    name: "unpackerr"
    image: "golift/unpackerr:latest"
    pull: yes
    networks:
      - name: app_network
    state: 'started'
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
      "UN_SONARR_0_URL": "http://sonarr:8989"
      "UN_SONARR_0_API_KEY": "{{ sonarr_api }}"
      "UN_RADARR_0_URL": "http://radarr:7878"
      "UN_RADARR_0_API_KEY": "{{ radarr_api }}"
      "UN_LIDARR_0_URL": "http://lidarr:8686"
      "UN_LIDARR_0_API_KEY": "{{ lidarr_api }}"
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "{{ mergerfs_root }}/Downloads:/downloads"
    restart_policy: unless-stopped
