---
- name: Make sure the linkding container is created and running
  docker_container:
    name: 'linkding'
    image: sissbruecker/linkding:latest
    networks:
        - name: app_network
    pull: yes
    state: 'started'
    env:
      "LD_SUPERUSER_NAME": '{{ linkding_admin }}'
      "LD_SUPERUSER_PASSWORD": '{{ linkding_admin_password }}'
    volumes:
        - '{{ docker_dir }}/linkding/data:/etc/linkding/data'
    restart_policy: unless-stopped
