---
- name: Make sure the dashdot container is created and running
  docker_container:
    name: 'dashdot'
    image: "mauricenino/dashdot"
    networks:
      - name: app_network
    pull: true
    state: 'started'
    restart_policy: unless-stopped
