---
- name: Create a adguard network
  docker_network:
    name: adguard_network
    ipam_config:
      - subnet: "{{ '.'.join(adguard_address.split('.')[0:3]) }}.0/27"
        gateway: "{{ '.'.join(adguard_address.split('.')[0:3]) }}.1"

- name: Make sure the adguard container is created and running
  docker_container:
    name: 'adguardhome'
    image: "adguard/adguardhome:latest"
    networks:
      - name: adguard_network
        ipv4_address: "{{ adguard_address }}"
      - name: app_network
    pull: false
    state: 'started'
    env:
      "TZ": "{{ timezone }}"
    volumes:
      - "{{ docker_dir }}/adguard/work:/opt/adguardhome/work"
      - "{{ docker_dir }}/adguard/conf:/opt/adguardhome/conf"
    ports:
      - "{{ lan_address }}:53:53/tcp"
      - "{{ lan_address }}:53:53/udp"
    restart_policy: unless-stopped
