---
- include_tasks: repo_arch.yml

- name: Make sure Nvidia drivers are installed
  become: true
  package:
    name:
      - "nvidia-driver-525"
    state: latest

- name: Add Nvidia GPG apt Key
  become: true
  shell:
    cmd: "curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | gpg --batch --yes --dearmour -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg"

- name: Add Nvidia Repository
  become: true
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://nvidia.github.io/libnvidia-container/stable/ubuntu18.04/$(ARCH) /"
    state: present
    filename: nvidia-container-toolkit

- name: Install nvidia-container-toolkit
  become: true
  package:
    name:
      - nvidia-container-toolkit
    state: latest

- name: Configure docker to recognise nvidia containter
  become: true
  shell:
    cmd: "sudo nvidia-ctk runtime configure --runtime=docker"

- name: Restart docker
  become: true
  service:
    name: docker
    state: reloaded

- name: Check if reboot required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot if required
  reboot:
    msg: Rebooting due to a kernel update
  when: reboot_required_file.stat.exists

- name: Increase max_user_watches for automatic import
  become: true
  blockinfile:
    path: /etc/sysctl.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: fs.inotify.max_user_watches=3276800

- name: Upgrade python docker via pip
  pip:
    name: docker
    state: latest

- name: Make sure the {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "ghcr.io/linuxserver/jellyfin:latest"
    networks:
      - name: app_network
    pull: true
    privileged: true
    device_requests:
      - driver: nvidia
        count: -1
        capabilities:
          - gpu
    state: 'started'
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
      "VERSION": "latest"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}:/config"
      - "{{ mergerfs_root }}/Media/Transcodes:/config/data/transcodes"
      - "{{ mergerfs_root }}/Media/Metadata:/metadata"
      - "{{ mergerfs_root }}/Media/Cache:/data/Cache"
      - "{{ mergerfs_root }}/Media/Movies:/data/Movies"
      - "{{ mergerfs_root }}/Media/Music:/data/Music"
      - "{{ mergerfs_root }}/Media/TV:/data/TV"
      - "{{ mergerfs_root }}/Media/Personal:/data/Personal"
      - "/etc/localtime:/etc/localtime:ro"
    restart_policy: unless-stopped
