---
- include_tasks: repo_arch.yml

- name: Make sure that Nvidia drivers are installed
  become: yes
  package:
    name:
      - "nvidia-driver-510"
    state: latest

- name: Add Nvidia GPG apt Key
  become: yes
  shell:
    cmd: "curl -sL https://nvidia.github.io/libnvidia-container/gpgkey | gpg --batch --yes --dearmour -o /etc/apt/trusted.gpg.d/nvidia.gpg"

- name: Add Nvidia Repository
  become: yes
  apt_repository:
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/nvidia.gpg] https://nvidia.github.io/libnvidia-container/stable/ubuntu18.04/$(ARCH) /"
    state: present
    filename: nvidia-docker

- name: Install nvidia-docker
  become: yes
  package:
    name:
      - nvidia-docker2
    state: latest

- name: Increase max_user_watches for automatic import
  become: yes
  blockinfile:
    path: /etc/sysctl.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: fs.inotify.max_user_watches=3276800

- name: Make sure the {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "ghcr.io/linuxserver/jellyfin:nightly"
    networks:
      - name: swag_public_macvlan
        ipv4_address: "{{ ip_address }}"
    pull: yes
    privileged: yes
    device_requests:
      - driver: nvidia
        count: -1
        capabilities:
          - gpu
    state: 'started'
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
      "VERSION": "latest"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}:/config"
      - "{{ mergerfs_root }}/Media/TV:/data/TV"
      - "{{ mergerfs_root }}_slow/Media/Transcodes:/config/data/transcodes"
      - "{{ mergerfs_root }}/Media/Metadata:/metadata"
      - "{{ mergerfs_root }}/Media/Cache:/data/Cache"
      - "{{ mergerfs_root }}/Media/Movies:/data/Movies"
      - "/etc/localtime:/etc/localtime:ro"
    restart_policy: unless-stopped
