---
- name: Create a photoprism network
  docker_network:
    name: photoprism_network

- name: Make sure the PhotoPrism MariaDB container is created and running
  docker_container:
    name: "photoprism-mariadb"
    image: "mariadb:latest"
    pull: yes
    networks:
      - name: photoprism_network
    command: "mariadbd --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120"
    state: 'started'
    env:
      "TZ": "{{ timezone }}"
      "MYSQL_ROOT_PASSWORD": "{{ mysql_root_password }}"
      "MYSQL_DATABASE": "nextcloud_db"
      "MYSQL_USER": "nextcloud"
      "MYSQL_PASSWORD": "{{ mysql_password }}"
    volumes:
      - "{{ docker_dir }}/photoprism/mariadb/mysql:/var/lib/mysql"
    restart_policy: unless-stopped


- name: Make sure the Photoprism container is created and running
  docker_container:
    name: "photoprism"
    image: photoprism/photoprism:latest
    networks:
      - name: photoprism_network
      - name: app_network
    pull: yes
    security_opts:
      - seccomp:unconfined
      - apparmor:unconfined
    state: 'started'
    shm_size: 2G
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "PHOTOPRISM_GID": "{{ guid }}"
      "PHOTOPRISM_UID": "{{ guid }}"
      "TZ": "{{ timezone }}"
      "PHOTOPRISM_ADMIN_PASSWORD": "{{ photoprism_password }}"
      "PHOTOPRISM_EXPERIMENTAL": "false"
      "PHOTOPRISM_HTTP_COMPRESSION": "gzip"
      "PHOTOPRISM_DATABASE_DRIVER": "mysql"
      "PHOTOPRISM_DATABASE_SERVER": "photoprism-mariadb:3306"
      "PHOTOPRISM_DATABASE_NAME": "nextcloud_db"
      "PHOTOPRISM_DATABASE_USER": "nextcloud"
      "PHOTOPRISM_DATABASE_PASSWORD": "{{ mysql_password }}"
      "PHOTOPRISM_DISABLE_CHOWN": "false"
      "PHOTOPRISM_DISABLE_BACKUPS": "true"
      "PHOTOPRISM_DISABLE_WEBDAV": "false"
      "PHOTOPRISM_DETECT_NSFW": "true"
      "PHOTOPRISM_UPLOAD_NSFW": "false"
      "PHOTOPRISM_THUMB_UNCACHED": "true"
      "PHOTOPRISM_JPEG_QUALITY": "92"
      "TF_CPP_MIN_LOG_LEVEL": "0"
      "PHOTOPRISM_FFMPEG_ENCODER": "h264_qsv"
      "PHOTOPRISM_INIT": "tensorflow-amd64-avx2"
    working_dir: "/photoprism"
    devices:
      - "/dev/dri/renderD128:/dev/dri/renderD128" # Intel GPU
    volumes:
      - "{{ mergerfs_root }}/Nextcloud/{{ username }}/files/Photos:/photoprism/originals"
      - "{{ docker_dir }}/photoprism/storage:/photoprism/storage"
    restart_policy: unless-stopped

- name: Schedule a library scan at 1 AM every day
  cron:
    name: Scan the PhotoPrism library
    hour: "1"
    minute: "0"
    job: "/usr/bin/docker exec photoprism /opt/photoprism/bin/photoprism index"
