---
- name: Make sure the cloudflare-ddns container is created and running
  docker_container:
    name: "cloudflare-ddns"
    image: "oznu/cloudflare-ddns:latest"
    pull: yes
    state: 'started'
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
      "API_KEY": "{{ cloudflare_dns_token }}"
      "ZONE": "{{ host }}"
      "PROXIED": "false"
      # "SUBDOMAIN": "*"
    restart_policy: unless-stopped
