---
- name: Make sure the lidarr container is created and running
  docker_container:
    name: "lidarr"
    image: "lscr.io/linuxserver/lidarr:latest"
    pull: yes
    networks:
      - name: app_network
    state: 'started'
    ports:
      - "8686:8686"
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "{{ docker_dir }}/lidarr/config:/config"
      - "{{ docker_dir }}/lidarr/custom-services.d:/custom-services.d"
      - "{{ docker_dir }}/lidarr/custom-cont-init.d:/custom-cont-init.d"
      - "{{ mergerfs_root }}:/tank"
    restart_policy: unless-stopped

- name: Schedule a RSgain scan at 2 AM every day
  cron:
    name: Scan the Music library
    hour: "2"
    minute: "0"
    job: "docker run -v -rm /mnt/storage/Media/Music:/mnt rsgain easy -S -m MAX /mnt"
