---
- name: Create a gramps network
  docker_network:
    name: gramps_network

- name: Make sure Gramps redis container is created and running
  docker_container:
    name: 'gramps-redis'
    image: 'redis:alpine'
    pull: yes
    networks:
      - name: gramps_network
    env:
      'PUID': '{{ guid }}'
      'PGID': '{{ guid }}'
      'TZ': '{{ timezone }}'
    restart_policy: unless-stopped

- name: Make sure Gramps celery container is created and running
  docker_container:
    name: 'gramps-celery'
    image: 'ghcr.io/gramps-project/grampsweb:latest'
    pull: yes
    networks:
      - name: gramps_network
    env:
      'GRAMPSWEB_TREE': 'Gramps Web'
      'GRAMPSWEB_CELERY_CONFIG__broker_url': 'redis://gramps-redis:6379/0'
      'GRAMPSWEB_CELERY_CONFIG__result_backend': 'redis://gramps-redis:6379/0'
      'GRAMPSWEB_RATELIMIT_STORAGE_URI': 'redis://gramps-redis:6379/1'
      'PUID': '{{ guid }}'
      'PGID': '{{ guid }}'
      'TZ': '{{ timezone }}'
    volumes:
      - '{{ docker_dir }}/gramps/users:/app/users'
      - '{{ docker_dir }}/gramps/indexdir:/app/indexdir'
      - '{{ docker_dir }}/gramps/thumb-cache:/app/thumbnail_dir'
      - '{{ docker_dir }}/gramps/cache:/app/cache'
      - '{{ docker_dir }}/gramps/secret:/app/secret'
      - '{{ docker_dir }}/gramps/media:/app/media'
      - '{{ docker_dir }}/gramps/db:/root/.gramps/grampsdb'
      - '{{ docker_dir }}/gramps/tmp:/tmp'
    command: 'celery -A gramps_webapi.celery worker --loglevel=INFO'
    restart_policy: unless-stopped

- name: Make sure Gramps container is created and running
  docker_container:
    name: 'gramps'
    image: 'ghcr.io/gramps-project/grampsweb:latest'
    pull: yes
    networks:
      - name: gramps_network
      - name: app_network
    env:
      'GRAMPSWEB_TREE': 'Gramps Web'
      'GRAMPSWEB_CELERY_CONFIG__broker_url': 'redis://gramps-redis:6379/0'
      'GRAMPSWEB_CELERY_CONFIG__result_backend': 'redis://gramps-redis:6379/0'
      'GRAMPSWEB_RATELIMIT_STORAGE_URI': 'redis://gramps-redis:6379/1'
      'PUID': '{{ guid }}'
      'PGID': '{{ guid }}'
      'TZ': '{{ timezone }}'
    volumes:
      - '{{ docker_dir }}/gramps/users:/app/users'
      - '{{ docker_dir }}/gramps/indexdir:/app/indexdir'
      - '{{ docker_dir }}/gramps/thumb-cache:/app/thumbnail_dir'
      - '{{ docker_dir }}/gramps/cache:/app/cache'
      - '{{ docker_dir }}/gramps/secret:/app/secret'
      - '{{ docker_dir }}/gramps/media:/app/media'
      - '{{ docker_dir }}/gramps/db:/root/.gramps/grampsdb'
      - '{{ docker_dir }}/gramps/tmp:/tmp'
    restart_policy: unless-stopped
