---
- name: Create an linkwarden network
  docker_network:
    name: linkwarden_network

- name: Make sure the linkwarden container is created and running
  docker_container:
    name: 'linkwarden'
    image: ghcr.io/linkwarden/linkwarden:latest
    networks:
        - name: app_network
        - name: linkwarden_network
    pull: yes
    state: 'started'
    env:
      "NEXTAUTH_SECRET": "choosing-profane-arose"
      "DATABASE_URL": "postgresql://linkwarden:ascent-levitator-basically@linkwarden-postgres:5432/linkwarden"
    volumes:
        - '{{ docker_dir }}/linkwarden/data:/data/data'
    restart_policy: unless-stopped

- name: Make sure the linkwarden-postgres container is created and running
  docker_container:
    name: 'linkwarden-postgres'
    image: postgres:16-alpine
    networks:
        - name: linkwarden_network
    pull: yes
    state: 'started'
    env:
      "POSTGRES_USER": "linkwarden"
      "POSTGRES_PASSWORD": "ascent-levitator-basically"
      "POSTGRES_DB": "linkwarden"
    restart_policy: unless-stopped
