- name: Install Neovim python modules
  pip:
    name:
      - pynvim

- name: Grab the latest Neovim release
  get_url:
    url: "https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.deb"
    dest: /tmp

- name: Install neovim
  become: true
  apt: deb="/tmp/nvim-linux64.deb"
