- name: Install Neovim python modules
  pip:
    name:
      - pynvim

- name: Grab the latest Neovim release
  get_url:
    url: "https://github.com/neovim/neovim/releases/download/stable/nvim.appimage"
    dest: /usr/local/bin/nvim

- name: Chmod nvim
  become: true
  file:
    path: /usr/local/bin/nvim
    state: file
    mode: 0755
    owner: root
    group: root
    recurse: no
