---
- name: Make sure the bazarr container is created and running
  docker_container:
    name: "bazarr"
    image: "linuxserver/bazarr"
    pull: yes
    networks:
      - name: app_network
    state: 'started'
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "{{ docker_dir }}/bazarr:/config"
      - "{{ mergerfs_root }}:/tank"
    restart_policy: unless-stopped
